name: finki-hub-recordings-listing-dev

services:
  site:
    build:
      context: .
    image: finki-hub/recordings-listing:latest
    ports:
      - "8080:80"
    pull_policy: never
    restart: unless-stopped
