name: finki-hub-recordings-listing-dev

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/finki-hub/recordings-listing:local
    ports:
      - "8080:80"
    restart: unless-stopped
