name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
    uses: finki-hub/.github/.github/workflows/vitest.yaml@main
    with:
      node-version: '24'
      test-args: ''
  deploy:
    needs: test
    uses: finki-hub/.github/.github/workflows/cloudflare-pages.yaml@main
    with:
      node-version: '24'
      project-name: finki-hub-recordings-listing
      directory: .vitepress/dist
    secrets: inherit
