name: Docker

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    permissions:
      contents: read
    uses: finki-hub/.github/.github/workflows/vitest.yaml@main
    with:
      node-version: '24'
      test-args: ''
  docker:
    needs: test
    uses: finki-hub/.github/.github/workflows/docker.yaml@main
    secrets: inherit
