name: E2E

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  playwright:
    uses: finki-hub/.github/.github/workflows/playwright.yaml@main
    with:
      install-command: npm ci --ignore-scripts
      test-command: npm run test:integration
