name: Linters

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analytics-tests:
    uses: finki-hub/.github/.github/workflows/vitest.yaml@main
    with:
      test-args: ''
  markdown-and-build:
    uses: finki-hub/.github/.github/workflows/docs-check.yaml@main
